# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'node install -s unblocker' # runs during prebuild
    command: echo 'node index.js'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
